server:
    port: 8099
spring:
    application:
        name: springboot-aliyunoss
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        name: defaultDataSource
        password: 123456
        url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
        username: root
    thymeleaf:
        cache: false
        check-template: true
        check-template-location: true
        content-type: text/html
        enabled: true
        encoding: UTF-8
        excluded-view-names: ''
        mode: HTML5
        prefix: classpath:/templates/
        suffix: .html

    # 上传文件大小限制
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 1024MB

# mybatisplus逻辑删除和打印sql
mybatis-plus:
    global-config:
        db-config:
            logic-delete-value: 1
            logic-not-delete-value: 0
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 阿里云OSS配置
aliyun:
    oss:
        accessKeyId: LTAI5tFjAPZ585HhAq4hrU65
        accessKeySecret: 0gr012A0juUIhOjNzD7Nckfey4v205
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: yang-aliyun-oss
        filehost: upload

# 本地资源
local:
    uploadPath: D:/upload/
